BEGIN;

REVOKE TRUNCATE, TRIGGER, REFERENCES, MAINTAIN
ON ALL TABLES IN SCHEMA "public"
FROM "anon", "authenticated"
RESTRICT;

ALTER DEFAULT PRIVILEGES
FOR ROLE "postgres"
IN SCHEMA "public"
REVOKE TRUNCATE, TRIGGER, REFERENCES, MAINTAIN
ON TABLES
FROM "anon", "authenticated"
RESTRICT;

COMMIT;
